inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'src/main.rb'
    - 'src/module/view/view.rb'

Metrics/AbcSize:
  Exclude:
    - 'src/controller.rb'
    - 'src/module/view/view.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'src/module/view/view.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
