inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'src/main.rb'

Metrics/AbcSize:
  Exclude:
    - 'src/controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
